[project]
name = "krr-project"
version = "0.1.0"
description = "OpenFGA inspired rule based engine"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.10",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
